version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo "Building..."
      - grep -Fq "Musician App" index.html
  post_build:
    commands:
      - echo "Code built!"
